apiVersion: v1
kind: Namespace
metadata:
  name: thr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: thr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:latest
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: uptime-kuma-data
              mountPath: /app/data
      volumes:
        - name: uptime-kuma-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-service
  namespace: thr
spec:
  selector:
    app: uptime-kuma
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP